### ISSUE TITLE
shit dont compile

### ISSUE THREAD

**Issue by ZyByte** [ARF-SS13/coyote-bayou#1001]
---- Testmerges: ----

---- Reproduction: ----

---- Screenshots: ----

---- Additional context: ----

**Comment by ZyByte** [comment]
My mistake. It does compile but this shit dont run. Dreamdaemon crashes with no error. I've tested other ss13 codebases, runs fine.

**Comment by WrongEnd** [comment]
did you compile with build.bat

**Comment by ZyByte** [comment]
Yes. It compiles fine but dreamdaemon simply closes with no error shortly after clicking 'go'. This is the only codebase I have the issue with. This is with a clean download and build. I have cleared all yarn caches, tgui. Byond version 514.1583. I built 2 other ss13 codebases and ran them fine so it seems to only be this repo.

**Comment by ZyByte** [comment]
Figured it out with the help of a friend. I don't have AVX2 instructions on my old ass cpu. Found auxmos and compiled it for my system.
