### ISSUE TITLE
Missing Loot for Deathclaw Labs

### ISSUE THREAD

**Issue by neri-ventado** [ARF-SS13/coyote-bayou#1019]
---- Testmerges: ----

no testmerges :)
---- Reproduction: ----

break into deathclaw labs (accessible through west-sewers + the nash ladder), do the bottom gutsy room and realize the lack of loot in the final two lockers
---- Screenshots: ----

![image](https://user-images.githubusercontent.com/71103211/197320728-f1e11e7a-ea67-4b42-b3aa-03ac83c6227c.png)

---- Additional context: ----

To find Deathclaw Labs, you first have to go down this ladder in Nash.
![image](https://user-images.githubusercontent.com/71103211/197320753-ddd7eceb-58bc-4ae1-92e9-fc179e82b3dc.png)
Go west in the tunnel, then north. 
The room next to Deathclaw Labs looks like this.
![image](https://user-images.githubusercontent.com/71103211/197320790-2752eddf-e1f0-4204-a95d-b3712711852b.png)

**Comment by AmethystTheSergal** [comment]
Looking at this now.

**Comment by AmethystTheSergal** [comment]
https://github.com/ARF-SS13/coyote-bayou/pull/1021

It's done.

**Comment by neri-ventado** [comment]
Thank you!
