### ISSUE TITLE
Gardeners' toolbelts don't seem to be able to hold ANYTHING

### ISSUE THREAD

**Issue by Cartlord** [ARF-SS13/coyote-bayou#1195]
---- Testmerges: ----
None

---- Reproduction: ----
Get a gardeners' toolbelt from the Farmer loadout, try to put any tool in it (e.g. cultivator, spade, plant analyzer, bucket), get told it can't be held by the belt.

---- Screenshots: ----

---- Additional context: ----

**Comment by xXPawnStarrXx** [comment]
I think I found the issue and hopefully this should resolve it.
https://github.com/ARF-SS13/coyote-bayou/pull/1340

**Comment by PrettyPsychoForAWolf** [comment]
Issue should be fixed with the pr. Moving to resolved once live testing proves as such.

**Comment by xXPawnStarrXx** [comment]
Yup, this is resolved, tested it in game the other day.
