### ISSUE TITLE
Durathread can be duplicated in massive quantities

### ISSUE THREAD

**Issue by Cartlord** [ARF-SS13/coyote-bayou#1196]
---- Testmerges: ----
None.

---- Reproduction: ----
Get a stack of raw cotton, any size. Get a stack of raw durathread, any size but preferably small. Hold the durathread in-hand. Click the cotton. All cotton moved to the durathread stack and converted to match.

**Comment by GremlingSS** [comment]
Just tested this and I can't reproduce the issue, are you testing on an older version like a month ago..? Just curious as there was an oversight with the stack.dm file Dan had done but it's been fixed.

**Comment by Cartlord** [comment]
Ah, I see the problem.
I was mistaenly redirected to here from a downstream.
My other issues might not stand either.
