### ISSUE TITLE
Prospectors could probably use a roundstart O.R.M.

### ISSUE THREAD

**Issue by Cartlord** [ARF-SS13/coyote-bayou#1199]
Prospectors need an O.R.M. to smelt shit, need stock parts to make an O.R.M., need metal & glass to make stock parts, and need either caps or an O.R.M. to get metals & glass without taking eye damage from hand-welding the ore. I believe this should change in some way, like by giving them all the parts in their garage at roundstart, or by just giving them an O.R.M. roundstart, making the Eastwood vault's ore silo be constructed roundstart, and having them both start linked.

**Comment by thingpony** [comment]
There's an ORM on the map, near the ant mound. Closing the issue.
