### ISSUE TITLE
Behemoth loot/exit button requers access you cant get

### ISSUE THREAD

**Issue by Heniyme** [ARF-SS13/coyote-bayou#1304]
---- Testmerges: ----

Round ID: 1109
BYOND Version: 514.1583
Server revision compiled on: 2022-12-08T20:28:01+00:00
Master commit: [7a6e5ddb62603f6aedefb60f47ef9e9e83104271](https://github.com/ARF-SS13/coyote-bayou/commit/7a6e5ddb62603f6aedefb60f47ef9e9e83104271)
TGS version: 4.17.1
DMAPI version: 5.3.0

---- Reproduction: ----
try to open any of thise buttons
![image](https://user-images.githubusercontent.com/120269086/206864935-d60255b3-ac77-4521-b22f-85c5b34ccba5.png)

---- Screenshots: ----
![image](https://user-images.githubusercontent.com/120269086/206864885-04a658d6-ab9b-4bf2-a13f-c67aec6cdec2.png)
![image](https://user-images.githubusercontent.com/120269086/206864892-2455a2c5-0ae6-43bc-b50a-a622efb2376c.png)

---- Additional context: ----
day ruined

**Comment by Tk420634** [comment]
You get the access from the behemoth when you kill it.
