### ISSUE TITLE
Preacher seems to have been overlooked in the recent loadout and faction cleanup/tweek

### ISSUE THREAD

**Issue by Hesjin** [ARF-SS13/coyote-bayou#1588]
---- Testmerges: ----
Round ID: 1474
BYOND Version: 514.1583
Server revision compiled on: 2023-02-25T05:06:21+00:00
Master commit: [62935ffef20b7eb83e98d3848341d942bc1c79d7](https://github.com/ARF-SS13/coyote-bayou/commit/62935ffef20b7eb83e98d3848341d942bc1c79d7)
TGS version: 5.2.3
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----
Preacher is still part of the Wastelander Faction, even after the recent faction cleanup, making them unable to access Nash locks such as the Bar or use the :h Nash comms channel.

Additionally, they still spawn was the old cube loadout, rather than the new satchel the other roles are getting.

**Comment by FuzzyFuzlet** [comment]
preacher needs a lot of love, and will get it, sooner or later. the job overhaul hasn’t yet impacted most jobs, only the basic ones for now, for live trials. each job will get updated in turn, slow and steady

**Comment by Hesjin** [comment]
Fair 'nuff! Thank you :V

**Comment by Tk420634** [comment]
job sunsetted
