### ISSUE TITLE
5.56 ammo boxes are invisible

### ISSUE THREAD

**Issue by JohnnyJohnJohnson** [ARF-SS13/coyote-bayou#1623]
---- Testmerges: ----
Round ID: 1506
BYOND Version: 514.1583
Server revision compiled on: 2023-03-03T06:54:48+00:00
Master commit: [1ae2ee2a25365d61fc03692762ff3f7b47ba8c20](https://github.com/ARF-SS13/coyote-bayou/commit/1ae2ee2a25365d61fc03692762ff3f7b47ba8c20)
TGS version: 5.2.4
DMAPI version: 5.3.0

---- Reproduction: ----

If you make 5.56 ammo boxes in a reloading bench, they are invisible. They still have an icon if you right click on them and they aren't invisible when empty, only invisible when they have bullets in them.

---- Screenshots: ----

---- Additional context: ----

**Comment by TalkingCactus** [comment]
Fixed
