### ISSUE TITLE
9mm Carbine is invisible when empty

### ISSUE THREAD

**Issue by ThatGuyPhil** [ARF-SS13/coyote-bayou#1735]
---- Testmerges: ----

---- Reproduction: ----
shoot the 9mm carbine until it is out of bullets, or just eject the magazine and clear the chamber. 
the sprite will vanish until you load a loaded magazine into it. 
fortunately you can still click on it even when invisible, but  you could probably lose it easilly.

---- Screenshots: ----

---- Additional context: ----

**Comment by FuzzyFuzlet** [comment]
the PR to fix this was merged a couple hours ago
