### ISSUE TITLE
Make Fireplaces Behave as Potbelly Stoves Do

### ISSUE THREAD

**Issue by Koboldfire** [ARF-SS13/coyote-bayou#1744]
Fireplaces should behave the same as potbelly stoves behave. Potbelly stoves can be fueled just like fireplaces do but they never fully extinguish, when their fuel is low they simply get dimmer and when refueled they become very bright. Fireplaces will however fully extinguish when they run low on fuel, and they burn through fuel extremely quickly which makes keeping a cozy atmosphere for a scene with them totally impractical.

**Comment by TalkingCactus** [comment]
Fixed in #2246
