### ISSUE TITLE
Auto Pipe Rifles are missing sprites

### ISSUE THREAD

**Issue by McRex007** [ARF-SS13/coyote-bayou#1769]
Round ID: 1691
BYOND Version: 514.1589
Server revision compiled on: 2023-03-25T05:32:02+00:00
Master commit: [af9605b12d0658f1916247511ec2c211a29793ca](https://github.com/ARF-SS13/coyote-bayou/commit/af9605b12d0658f1916247511ec2c211a29793ca)
TGS version: 5.2.4
DMAPI version: 5.3.0

Auto Pipe Rifles do not have any big/icon/on ground sprites. Belt in, belt out but one in the chamber, and cleared are all missing. Sprites in hand work as expected. They currently are a somewhat rare spawn in trash piles. From my very limited experience with matters like this, its possible the dmi the sprites are in was moved or renamed.

![pipe rifle](https://user-images.githubusercontent.com/30481894/227726914-1cb6c5d7-341c-4059-b34b-bc817fdd271b.png)

**Comment by Tk420634** [comment]
lol fixed who knows when
