### ISSUE TITLE
Hells Nomad's Battle Coats Have No Armor

### ISSUE THREAD

**Issue by neri-ventado** [ARF-SS13/coyote-bayou#1795]
---- Testmerges: ----

NO TESTMERGES.
---- Reproduction: ----

SPAWN IN AS A HELLS NOMAD.
OPEN THE ARMOR LOCKER, INSPECT COATS.
CRY.

---- Screenshots: ----

![image](https://user-images.githubusercontent.com/71103211/228383671-66733cd1-44d8-4da8-b348-188e9652fc29.png)

---- Additional context: ----

**Comment by HanSolo1519** [comment]
wow, whoever made the map must suck
