### ISSUE TITLE
Portable IV from loadout bugs out and can't be retrieved.

### ISSUE THREAD

**Issue by RadiantFlash7** [ARF-SS13/coyote-bayou#1863]
---- Testmerges: ----

Round ID: 1766
BYOND Version: 514.1589
Server revision compiled on: 2023-04-03T06:55:37+00:00
Master commit: [547494ed9dfab1e31914fcc14417dc0433253d9f](https://github.com/ARF-SS13/coyote-bayou/commit/547494ed9dfab1e31914fcc14417dc0433253d9f)
The following pull requests are currently test merged:
[#1797: 'Automatic TGS DMAPI Update' by github-actions[bot] at commit 3f1c0d9b6d](https://github.com/ARF-SS13/coyote-bayou/pull/1797)

Local commit: 4284bfe3ca010be0eb89cb43c8592a4e5cc9f31f
TGS version: 5.2.4
DMAPI version: 5.4.0
---- Reproduction: ----

Spawn in as a wastelander, select the medical load out and then surgery. You should have a portable IV in the bag. But it isn't there.
However, emptying the bag out for everything else leaves it behind with it showing 'nothing' inside it. Per an admin, it's still there in the vars, but I have no way to see or remove it. Emptying it onto the floor did nothing.
---- Screenshots: ----
![image](https://user-images.githubusercontent.com/12434413/229672818-6743f207-a042-4f76-8d50-3ed6691c70df.png)
![image](https://user-images.githubusercontent.com/12434413/229672846-f5cc46bb-d1e0-41c0-a9ed-30c446d171d6.png)
![image](https://user-images.githubusercontent.com/12434413/229672867-4cc30865-1ac0-4a26-8517-f8261a001d50.png)

---- Additional context: ----

**Comment by RadiantFlash7** [comment]
If I had to /guess/ I'd say it's because it's extended on initial spawn, possibly? Rather then being folded up? But I really don't know.

**Comment by GremlingSS** [comment]
Aha, knew it, it's because it's an "/obj/machinery" not an "/obj/item/"
This is because machines don't have code to be put into inventories, or to be picked up really.
Will supply a fix soon
