### ISSUE TITLE
Boosters and other weapon mods for energy weapons aren't functioning properly.

### ISSUE THREAD

**Issue by knoxon1** [ARF-SS13/coyote-bayou#2104]
---- Testmerges: ----
Round ID: 1995
BYOND Version: 514.1589
Server revision compiled on: 2023-04-29T02:21:39+00:00
Master commit: [a5d807a900da99e3c8a17483309250f706670ce1](https://github.com/ARF-SS13/coyote-bayou/commit/a5d807a900da99e3c8a17483309250f706670ce1)
TGS version: 5.2.4
DMAPI version: 5.6.0

---- Reproduction: ----
When attaching weapon mods such as boosters, giga lenses and high powered motors; mods that increase an energy weapon projectile damage at cost of cell charge per shot, the cost of each shot will increase exponentially until the weapon is unusable. I have tested the mods on all common energy weapons (Wattz, AER and AEPs, Plasmas) and it appears to affect all of them.

**Comment by Tk420634** [comment]
All mods were overhauled recently, this doesn't seem to be an issue any more
