### ISSUE TITLE
45 LC bag and Box both randomly spawn with 0 Ammo or...

### ISSUE THREAD

**Issue by lowpowermia** [ARF-SS13/coyote-bayou#2385]
---- Testmerges: ----
Round ID: 2183
BYOND Version: 514.1589
Server revision compiled on: 2023-05-20T20:42:59+00:00
Master commit: [11444f368d9744387c1ca0b880c520bff0bae5ea](https://github.com/ARF-SS13/coyote-bayou/commit/11444f368d9744387c1ca0b880c520bff0bae5ea)
TGS version: 5.2.4
DMAPI version: 5.6.0

---- Reproduction: ----

Make some 45 LC ammo. (handloaded or box)
Realize you got 0 bullets. 
Put it back into the bullet lathe for 1/6th the metal.
Continue to lose metal, gambling to make ammo for your bouncy gun.

---- Screenshots: ----
![image](https://github.com/ARF-SS13/coyote-bayou/assets/19172834/67fda6cc-f73b-4494-8569-73abe8c614e7)

---- Additional context: ----
   😢 
👉 👈  
please make the funny 45 lc revolvers selectable in the uncommon gun selection too? They're available in the uncommon random crate, but not in the inhand selection box you can buy for more.

**Comment by Tk420634** [comment]
fixed god knows when
