### ISSUE TITLE
Remove RND as a thing

### ISSUE THREAD

**Issue by Tasald** [ARF-SS13/coyote-bayou#2513]
Researching the tech over n over in game is tedious, and slightly immersive breaking in my opinion. 

I suggest just removing it entirely, but replace the 'protolathe' with something that can print at most t2/t3 parts and tech. ((as well as plant data discs plz)). Also if it can print stuff for borgs, that would be nice since I belive there a few that wana play borgos.

Alota the stuff in the rnd tree isn't even used. mechs are almost useless, plumbing maybe? even alota the mining stuff goes unused.

What i'd like to see in the lathe:

Basic parts
Advanced parts+rped
Hyper cells? (which ever the t2 is)
that circute stuff people like diddling with
Basic prosthetics
Basic organs
x large beaker and advanced health analyzer
maybe west tech surgical tools/ power tools. (resoning since scientists spawn with power tools anyway?) at a steep resource/coin cost
printable basic borg parts (flashs, limbs, frame, restart board, rename board, ect?)
telescopic iv stand, roller beds, wheel chairs, organ box
be able to print a blood bank board ((would be nice))
printable vendor boards

add an auto surgeon to the implant vendor?

stuff like t3/4 parts would only be loot stuff or 'maybe' from the trader, along with the bluespace rped, maybe some other boards like mech boards or parts?

this is very rough rn though.

**Comment by CacheAtWork** [comment]
I like this idea. I'm going to take a look into it, however I won't be adding the circuitry stuff as it's incredibly abusable and there was a reason it was removed in citadel code. The rest of it, however is pretty much good ideas.
