### ISSUE TITLE
Shapely shirt sprite clipping.

### ISSUE THREAD

**Issue by TrickingTrapster** [ARF-SS13/coyote-bayou#2521]
---- Testmerges: ----
Round ID: 2339
BYOND Version: 514.1589
Server revision compiled on: 2023-06-14T01:35:15+00:00
Master commit: [6ef41d96ec8dcda26878a46510c4197c2684ec52](https://github.com/ARF-SS13/coyote-bayou/commit/6ef41d96ec8dcda26878a46510c4197c2684ec52)
The following pull requests are currently test merged:
[#2508: 'Reworks recoil into something I can understand' by Superlagg at commit 37930c962e](https://github.com/ARF-SS13/coyote-bayou/pull/2508)

Local commit: 5136a4cb775960372f2a5b828f511273f31b8eed
TGS version: 5.2.4
DMAPI version: 5.6.1

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----

Easy, the sprite for the shapely undershirt (More specifically the big ones) are apparently lower priority than and 'bottom' clothes you equip, making it look like you tucked your boobs into your skirt or pants. Hands also go in front of it. And the bigger ones also don't seem represented from the back.

---- Screenshots: ----
Sorry, I don't have good screenshotting software. :/

---- Additional context: ----
First round testing it out, but the clipping is very distracting, especially from the front, but the sides also have some shades of it.

**Comment by Tk420634** [comment]
fixed
