### ISSUE TITLE
Ammunition Vendors - Slugs purchases come out as Buckshot

### ISSUE THREAD

**Issue by SpiritAngler** [ARF-SS13/coyote-bayou#2596]
---- Testmerges: ----
Round ID: 2448
BYOND Version: 514.1589
Server revision compiled on: 2023-07-02T19:07:47+00:00
Master commit: [5a1cf139f0b21086cb68594ca56611fb0a85cec5](https://github.com/ARF-SS13/coyote-bayou/commit/5a1cf139f0b21086cb68594ca56611fb0a85cec5)
The following pull requests are currently test merged:
[#2588: 'Berserker Rework!' by RinPin at commit 871fb7869b](https://github.com/ARF-SS13/coyote-bayou/pull/2588)

Local commit: c10aad46a036668d4c49dd8fd0d65cd455052645
TGS version: 5.2.4
DMAPI version: 5.6.1

---- Reproduction: ----

Very simple. Approach ammo vendor, attempt to buy the 12 Gauge Slug box. You'll get a box of buckshot. It might be named 'slugs,' but it isn't. It's buckshot.

---- Additional context: ----

Make it more expensive, probably. Slugs are nuts- actually, just make bullets more expensive in general.

**Comment by Tk420634** [comment]
fixed
