### ISSUE TITLE
Incorrect names for vertibird landing locations

### ISSUE THREAD

**Issue by Dangerlurking** [ARF-SS13/coyote-bayou#2608]
Some of the landing areas for the vertibird are incorrect, mostly involving Redwater landing zones. For example; the landing zone labeled "Wilderness north of Redwater" is actually just west of Redwater by the bridge, and the location labeled west of Redwater is actually west of the penitentiary and isn't involved with Redwater at all.

**Comment by Tk420634** [comment]
fixed, broken, and refixed long ago lol
