### ISSUE TITLE
Zoomies and Super Zoomies prevent you from sprinting at all.

### ISSUE THREAD

**Issue by LiteralMushroom** [ARF-SS13/coyote-bayou#2666]
It still makes the noise, but it doesn't actually speed you up or consume the buffer.

The toggle and holding down shift both don't work.

---- Testmerges: ----
https://github.com/ARF-SS13/coyote-bayou/assets/79603707/cad7e520-958e-4c1b-9205-6f9d2576f780

---- Reproduction: ----
Take the Zoomies or Super Zoomies trait.
Realize you can't sprint.

**Comment by Tk420634** [comment]
Zoomies was fully fixed by cactus back in november, or should be.  Closing this for now.  If they break again beat me with a rock.
