### ISSUE TITLE
You are using stolen content.

### ISSUE THREAD

**Issue by lambsie11** [ARF-SS13/coyote-bayou#2707]
I see that you have taken content from other SS13 codebases without asking. I recommend you remove the stolen content.

**Comment by EtheoBoxxman** [comment]
If you can point out what content was 'stolen', Im sure things can be rectified. Being vague like this helps noone.

**Comment by GremlingSS** [comment]
Hi, sorry for violating the license terms, we're working to fix this.

Your assets are under the AGPL license for the code. However we weren't aware that you had a CC by SA v3 license for your icons and sounds.

I hate to be the bearer of bad vibes, but we aren't stealing assets which is general public. (Although now we discovered it's creative commons share-alike)

However we will credit the source code and follow the correct licensing terms. Having CC by SA v3 for your assets basically opens it up to getting "stolen".

I'll work on this soon. Ya boi got the COVID-20 (the sequel) and I'm just absolutely dying rn.
