### ISSUE TITLE
Fenny borked all dna manipulators

### ISSUE THREAD

**Issue by Pokebutt** [ARF-SS13/coyote-bayou#2913]
---- Testmerges: ----

---- Reproduction: ----

get any dna manipulator and try to add a disk, you cant add it regardless of having the technofreak quirk or chemistry

---- Screenshots: ----

https://imgur.com/a/2H0oyU3
---- Additional context: ----
it doesnt let you add disks regardless of manipulator

**Comment by Tasald** [comment]
this is fixed, init?
