### ISSUE TITLE
Imitation stimfluid hurts you after it heals you

### ISSUE THREAD

**Issue by McRex007** [ARF-SS13/coyote-bayou#3081]
---- Testmerges: ----

[#3067: 'Sepia Filter Sunlight Experiment' by Tk420634 at commit bb536f7e0d](https://github.com/ARF-SS13/coyote-bayou/pull/3067)
---- Reproduction: ----

Healing with imitation stimfluid heals you instantly, like stimfluid, but then also causes you to take some brute and burn damage. Some amount of imitation stimflud is left over, which is presumably doing it as it metabolizes.
---- Screenshots: ----

---- Additional context: ----

Before it was removed, imitation stimfluid was basically just super bicaridine and kelotane. It healed at the same rate as both, but healed both damage types as it metabolized, and was orange. The current implementation seems to be more like the current stimfluid, which heals instantly. Making it more of a metabolizer than an instant heal could differentiate it from stimfluid more and help ensure it doesn't steal stimfluids spotlight. Tested with 10u doses, so I don't think its overdosing.

**Comment by thingpony** [comment]
Intented.
