### ISSUE TITLE
Splashing copper onto metal doesn't make bronze

### ISSUE THREAD

**Issue by McRex007** [ARF-SS13/coyote-bayou#3085]
---- Testmerges: ----

[#3067: 'Sepia Filter Sunlight Experiment' by Tk420634 at commit bb536f7e0d](https://github.com/ARF-SS13/coyote-bayou/pull/3067)
---- Reproduction: ----

When splashing equal amounts copper onto metal, 1u per sheet, nothing happens. It should result in bronze (which is now renamed black bronze).
---- Screenshots: ----

---- Additional context: ----

It might've been changed to be done another way, as I saw some yesterday, albiet not being made.

**Comment by EtheoBoxxman** [comment]
Splash copper onto plasteel for bronze now, change was made about a week ago to justify bronze doing 10% more damage than iron and titanium.
