### ISSUE TITLE
Duplicate gate buttons in Nash

### ISSUE THREAD

**Issue by Kilmented** [ARF-SS13/coyote-bayou#3308]
---- Testmerges: ----
Round ID: 3131
BYOND Version: 514.1589
Server revision compiled on: 2023-10-06T23:00:41+00:00
Master commit: [21abcbfb4fa9c3f96982bcc8205ccce373d6940c](https://github.com/ARF-SS13/coyote-bayou/commit/21abcbfb4fa9c3f96982bcc8205ccce373d6940c)
The following pull requests are currently test merged:
[#3256: 'Fix some runtimes!' by DameonOwen at commit 4d5df7737c](https://github.com/ARF-SS13/coyote-bayou/pull/3256)
[#3306: 'disables leaving the game!' by Superlagg at commit cd7a1cb3c8](https://github.com/ARF-SS13/coyote-bayou/pull/3306)

Local commit: ff672d78e178167f529512f357688604ac753487
TGS version: 5.2.4
DMAPI version: 5.6.1

---- Reproduction: ----

Walk to Nash, deconstruct the gate buttons.

---- Screenshots: ----

![image](https://github.com/ARF-SS13/coyote-bayou/assets/80431951/6e6c5e13-57af-438d-8281-fbef17556f5b)

---- Additional context: ----
There's two buttons :<

**Comment by Tk420634** [comment]
you smell
