### ISSUE TITLE
{BUG} Paper Bundles/Paper Trays are uninteractable

### ISSUE THREAD

**Issue by Kegsey** [ARF-SS13/coyote-bayou#348]
---- Testmerges: ----

[f70910bb221f8b35655f0edc6ab4f98c6c3e23a2](https://github.com/ARF-SS13/coyote-bayou/commit/f70910bb221f8b35655f0edc6ab4f98c6c3e23a2)
---- Reproduction: ----
Try to interact with papertrays/paper bundles, byond picking it up nothing can be done.

**Comment by GremlingSS** [comment]
Fixed in #373
