### ISSUE TITLE
Two laser weapons have no export value

### ISSUE THREAD

**Issue by DiscordWizard** [ARF-SS13/coyote-bayou#3589]
---- Testmerges: ----

Round ID: 3344
BYOND Version: 514.1589
Server revision compiled on: 2023-10-25T11:24:23+00:00
Master commit: [80df790dd9519b29538a1e4c12297f68b157ec2d](https://github.com/ARF-SS13/coyote-bayou/commit/80df790dd9519b29538a1e4c12297f68b157ec2d)
TGS version: 5.2.4
DMAPI version: 5.6.2

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----
Spawn, pick laser pistol and laser carbine loadout, scan with an export scanner linked to an export console

---- Screenshots: ----
![imagen](https://github.com/ARF-SS13/coyote-bayou/assets/34355419/39c6455d-9436-4dd2-b3a9-14d4c9e4f5b8)

---- Additional context: ----

**Comment by Kelprunner** [comment]
Son of a... Should be a fix within a day or so.

**Comment by Kelprunner** [comment]
https://github.com/ARF-SS13/coyote-bayou/pull/3657

This PR fixes this, along with a few other things.
