### ISSUE TITLE
ATM in downstairs of bank selling single silver coins at half expected rate, free money

### ISSUE THREAD

**Issue by SpiritAngler** [ARF-SS13/coyote-bayou#3611]
---- Testmerges: ----

Round ID: 3354
BYOND Version: 514.1589
Server revision compiled on: 2023-10-26T23:51:51+00:00
Master commit: [e72a7cbe0b305ba917dc1b47db5614919dbe7ef4](https://github.com/ARF-SS13/coyote-bayou/commit/e72a7cbe0b305ba917dc1b47db5614919dbe7ef4)
TGS version: 5.2.4
DMAPI version: 5.6.2

---- Reproduction: ----

Approach ATM in Nash Bank. Put in 6 eddies. Buy a silver coin, put it back in. You now have generated 4 copper and can repeat ad infinitum.

---- Screenshots: ----

![5PINXezaFY](https://github.com/ARF-SS13/coyote-bayou/assets/19819054/3b15e43a-583f-4813-9eba-df9ade8dd87c)

---- Additional context: ----

Mentioned it a few times in a couple places and have seen it used/abused, hopefully this will get it quashed.

**Comment by Kelprunner** [comment]
I... Why is it *6* instead of 11? Guh, thanks for catching this.

**Comment by Kelprunner** [comment]
https://github.com/ARF-SS13/coyote-bayou/pull/3657

Should be fixed when this is merged.
