### ISSUE TITLE
butt sprite layers over the tail

### ISSUE THREAD

**Issue by ThatGuyPhil** [ARF-SS13/coyote-bayou#3650]
---- Testmerges: ----

#3647: 'Just a rogue thought, don't mind this pr.  Probably not important.' by Tk420634 at commit 6c8d4fd248
---- Reproduction: ----
get big butt + any tail
join game
make butt visible
observe

---- Screenshots: ----

How it should look:
![image](https://github.com/ARF-SS13/coyote-bayou/assets/50330177/774a2a4e-8dd3-4d32-a8b7-5a26b1877225)

How it looks ingame:
![image](https://github.com/ARF-SS13/coyote-bayou/assets/50330177/2c3c256d-0342-4370-99e0-24b9573a456f)

---- Additional context: ----

**Comment by Tk420634** [comment]
This is just a layering bug, it should be happening even with that pr off.  lmao  Thanks tho!

**Comment by ThatGuyPhil** [comment]
Oh I only put that there because it was being testmerged at the time of reporting idk if it had to be the cause of the bug or not

**Comment by Tk420634** [comment]
fixed recently
