### ISSUE TITLE
The peacekeeper cannot swap fire modes

### ISSUE THREAD

**Issue by Pokebutt** [ARF-SS13/coyote-bayou#371]
the peacekeeper is stuck on auto fan the hammer mode which is an incredibly terrible mode
---- Testmerges: ----

---- Reproduction: ----

---- Screenshots: ----

---- Additional context: ----

**Comment by GremlingSS** [comment]
I dont think it has a fire mode setting, I think commenting out `	actions_types = list(/datum/action/item_action/toggle_firemode)
` on line 420 in Revolver.dm

**Comment by GremlingSS** [comment]
Fixed in a PR so :yeet:
