### ISSUE TITLE
Nest Stuffing Bug

### ISSUE THREAD

**Issue by Tk420634** [ARF-SS13/coyote-bayou#381]
You can switch hands while closing a nest and the closing bar continues to play out, this MAY be okay, but I want to record it for the sake of knowing it is a thing we might want to fiddle with.

**Comment by GremlingSS** [comment]
bro leave the template on because i cant remember if this was before or after the nest changes :'v

**Comment by GremlingSS** [comment]
This is a skill issue, simply because of the design of the code, do_after doesn't stop if you switch hands, honestly, I think it's fine.
