### ISSUE TITLE
Wheeless Wheelchairs - Bugged sprite

### ISSUE THREAD

**Issue by Faire-Fuzzy** [ARF-SS13/coyote-bayou#388]
Wheelchairs lack wheels on the east and west facing sprites and don't layer properly layer over the character sitting in them on the north facing face.

ALSO: Wheelchair users can go up stairs but not down them.

---- Testmerges: ----
Round ID: 168
BYOND Version: 514.1583
Server revision compiled on: 2022-07-21T15:07:28+00:00
Master commit: [02f2a931b9fde2ccd1f4a8b4ece5f03b91270f7b](https://github.com/ARF-SS13/coyote-bayou/commit/02f2a931b9fde2ccd1f4a8b4ece5f03b91270f7b)
TGS version: 4.17.1
DMAPI version: 5.3.0

---- Reproduction: ----
Sit and roll away in a wheelchair.

---- Screenshots: ----
![image](https://user-images.githubusercontent.com/16909237/180375596-eee9fb9f-04e8-456e-b733-029ee356b18e.png)
![image](https://user-images.githubusercontent.com/16909237/180375616-e2a141cf-f04b-43ba-9eb0-ff4ec97e7116.png)
![image](https://user-images.githubusercontent.com/16909237/180375623-d12a9aa1-540d-4a06-b87d-2da8894fd798.png)

---- Additional context: ----
No audio on movement as well, but that's a bit of a blessing given what audio /tg/ uses for them.

**Comment by GremlingSS** [comment]
I will fixeth this noweth, sorry about that.
an oversight on my end.
