### ISSUE TITLE
User-created areas are unpowered

### ISSUE THREAD

**Issue by Jamini** [ARF-SS13/coyote-bayou#431]
---- Testmerges: ----
Live
---- Reproduction: ----
1. Construct a viable room
2. Designate the room from the area construction button on the HUD
3. Place any powered equipment inside
4. Observe as it has no power!

---- Additional context: ----

Expected Behavior: New zones should have their universal power set to 1. As APCs are not buildable AND basic wasteland tiles have power.

Actual Behavior: When you designate a new zone, it loses all power. This makes all devices that use power (chargers, microwaves, blenders, chemistry equipment, and workshops) unusable

Notes: You lose power in a tile by designating it as part of a new room

**Comment by EtheoBoxxman** [comment]
PR put up for this 
https://github.com/ARF-SS13/coyote-bayou/pull/2702

**Comment by CASEYGUNGEON** [comment]
this issue was never closed when #2702 was merged
