### ISSUE TITLE
Requests tab in cargo console bluescreens TGUI

### ISSUE THREAD

**Issue by Ridley41** [ARF-SS13/coyote-bayou#4668]
---- Testmerges: ----
Round ID: 4068
BYOND Version: 515.1633
Server revision compiled on: 2024-03-18T03:01:53+00:00
Master commit: [d111cec6268fa5a24f5487b0749e5ca69bdd9f2c](https://github.com/ARF-SS13/coyote-bayou/commit/d111cec6268fa5a24f5487b0749e5ca69bdd9f2c)
The following pull requests are currently test merged:
[#4507: 'TGUIifies the flirt menu' by Superlagg at commit 3a251aea64](https://github.com/ARF-SS13/coyote-bayou/pull/4507)

Local commit: 2cd90f998e03dfd4ece4a9dbff6026339e075332
TGS version: 5.2.4
DMAPI version: 5.9.0

---- Reproduction: ----

Attempt to switch to the requests tab on the cargo console, TGUI will crash and display an error about the undefined variable CoinUnit
---- Screenshots: ----

[](https://gyazo.com/63b3df7cadd83bbd72ee71917a8cdada)

---- Additional context: ----

**Comment by Ridley41** [comment]
https://gyazo.com/63b3df7cadd83bbd72ee71917a8cdada

screenshot here since it didn't post for some reason

**Comment by Tk420634** [comment]
Fixed already
