### ISSUE TITLE
Remove or heavily nerf the cleaving axe from the head hunter

### ISSUE THREAD

**Issue by Shadow-Quill** [ARF-SS13/coyote-bayou#483]
The old trope of giving the lead roles uber powerful weapons always leads to bad things. the cleaving saw in particular is a one handed autoaxe with reach and damage over time, and needa yeeted

**Comment by Superlagg** [comment]
Cleaving axe has been changed significantly since its been posted, need to see if its good now. Havent seen people use it, so it might be a lot less powerful!

**Comment by bearrrrrrrr** [comment]
it's honestly not that good anymore. tbh might make it craftable
