### ISSUE TITLE
Some player preferences not saving.

### ISSUE THREAD

**Issue by gozulio** [ARF-SS13/coyote-bayou#515]
---- Testmerges: ----
Round ID: 291
BYOND Version: 514.1583
Server revision compiled on: 2022-08-04T17:42:03+00:00
Master commit: [8d46d8930d922250d7d5c15d0bf2a294f58fee8e](https://github.com/ARF-SS13/coyote-bayou/commit/8d46d8930d922250d7d5c15d0bf2a294f58fee8e)
TGS version: 4.17.1
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----

Open the set up character menu and change any of the effected settings listed bellow.
Click save setup.
Wait for the server restart.
The affected settings will have reverted to what they where originally.

---- Screenshots: ----

N/A

---- Additional context: ----
Some profile settings do not save correctly between rounds.
Known settings that have this issue:
Admin OOC/Antag OOC text color.
Sound indicator.

This issue seems to behave differently between different users. I suspect it to be an issue with how player save data is being handled, i.e. the save files not being loaded, saved, or generated/updated correctly after a patch that adds or removes settings..

**Comment by gozulio** [comment]
We never actually get to execute our code because the parent procs return.

https://github.com/ARF-SS13/coyote-bayou/blob/a6b463e3288fdbeaafbc0487d255438245440503/code/modules/client/preferences_savefile.dm#L337

https://github.com/ARF-SS13/coyote-bayou/blob/a6b463e3288fdbeaafbc0487d255438245440503/modular_coyote/code/modules/hair_gradient/hair_gradient.dm#L63-L67

https://github.com/ARF-SS13/coyote-bayou/blob/a6b463e3288fdbeaafbc0487d255438245440503/code/modules/client/preferences_savefile.dm#L897

https://github.com/ARF-SS13/coyote-bayou/blob/a6b463e3288fdbeaafbc0487d255438245440503/modular_coyote/code/modules/hair_gradient/hair_gradient.dm#L80-L82

**Comment by GremlingSS** [comment]
Fixed as it was a BYOND engine limitation, it locks the file and doesn't warn us about the file being locked or anything.
So we were reading nothing from the file, rather than it being read normally, its likely caused by too much external files being loaded while the server is online. It's VERY strange. It's been fixed however with the #1190 update.
