### ISSUE TITLE
Issues with the Chardir 'view' button

### ISSUE THREAD

**Issue by Aphast** [ARF-SS13/coyote-bayou#5218]
---- Testmerges: ----

Round ID: 4425
BYOND Version: 515.1633
Server revision compiled on: 2024-05-25T02:55:40+00:00
Master commit: 092806326697031ea492b17e0073378762179ccb
TGS version: 5.2.4
DMAPI version: 5.9.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
---- Reproduction: ----
open chardir, click 'view' button, for some it appears, for some it doesnt. Currently as of writing, only 2/6 player listings work, none of which are my own. Character names or details not provided to respect privacy. However the fact that it does not work for my own leads me to believe there may be some sort of cache corruption I have missed despite 2 reinstalls and a documents/byond clearing (Maybe resources for cb have not downloaded properly?). 

Method
click button, no worky ~16% gamble.

---- Screenshots: ----

![image](https://github.com/ARF-SS13/coyote-bayou/assets/75702012/73d2d60c-70a5-45e8-bac4-294b70605b0b)
Only entries 2 and 4 work, with 1 being my own.
---- Additional context: ----
Possibly relevant: CB's Icon has also stopped showing in the taskbar, instead showing a default orange dreamseeker logo

The f-list tab also still seems to work fine so... who knows, possible bug with driver versions and 514 or some shit.

Using most recent AMD drivers and Adrenalin software, no updates to be seen on the horizon.

**Comment by Superlagg** [comment]
What version byond are you using?

**Comment by NopemanMcHalt** [comment]
Reporting in the same issues:
1. CharDir "View" button doesn't work sometimes, only a few selections work.
2. Coyote Bayou server window doesn't have icon, despite it being here previously.

BYOND Version:
![image](https://github.com/ARF-SS13/coyote-bayou/assets/36963049/110182ce-e07c-4809-baa6-b888dc8f3018)

**Comment by Aphast** [comment]
> What version byond are you using?

Most recent 515, reinstalled twice from website

**Comment by Aphast** [comment]
After more testing I can confirm it is specific profiles that work consistently, as in I can always view specific people, between rounds, but anyone but those few randoms it is not working.

**Comment by Aphast** [comment]
**!! Confirmed cause found, byond version 515.1639 has a tgui bug preventing the use, downgrading to 515.1637 has been tested by myself to be a fix !!**

**Comment by NopemanMcHalt** [comment]
On newer `515.1640` issue with chardir *seems to* be fixed, I think. But the CB's Icon still not working.
