### ISSUE TITLE
Aim Crosshair miss when equip a Firearm Gun.

### ISSUE THREAD

**Issue by Leonister** [ARF-SS13/coyote-bayou#934]
The aim miss when i equip a gun on hand, just get invisible.
Tried to download a older version, but still bugged.
Thats make impossible to shoot because i can see the aim, the mouse point get invisible if i equip a gun.

You guys can make a Option to turn off the Aim and put the mouse pointer to aim? Its a good idea if someone take the same problem.

**Comment by Tk420634** [comment]
incomprehensible issue
